# Generated by Django 5.0.1 on 2024-01-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzashop',
            name='url',
        ),
    ]
