# Generated by Django 5.0.1 on 2024-01-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_remove_pizzashop_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzashop',
            name='url',
            field=models.URLField(default=0, verbose_name='Internet_address'),
            preserve_default=False,
        ),
    ]
