# Generated by Django 5.0.1 on 2024-01-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_pizza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'Pizza', 'verbose_name_plural': 'pizzas'},
        ),
        migrations.AlterModelOptions(
            name='pizzashop',
            options={'verbose_name': 'PizzaShop', 'verbose_name_plural': 'pizzashops'},
        ),
    ]
